name: SonarCloud Scan

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Adjust the Python version as needed

      - name: SonarCloud Scan
        run: |
          python -m pip install -r requirements.txt  # Install your project dependencies
          sonar-scanner \
            -Dsonar.projectKey=yashikesh_yashikesh
            -Dsonar.organization=yashikesh
            -Dsonar.sources=. \
            -Dsonar.python.coverage.reportPaths=coverage.xml  # If you have coverage reports
          # Additional SonarCloud parameters can be added as needed
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
